### ISSUE TITLE
Add option for starts-with / ends-with for string searches

### ISSUE THREAD

**Issue by seanthomasdevlin** [Servoy/svySearch#10]
Default behavior is currently _contains_ and cannot be changed
Ideally this is done per SearchProvider

Something like:

```
simpleSearch.addSearchProvider('my_column')
    .setStringMatching(scopes.svySearch.STRING_MATCH.STARTS_WITH)
```

**Comment by kimpremuda** [comment]
Yes, string matching should be performed on a per SearchProvider basis. No need to change default behavior.

**Comment by vschuurhof-servoy** [comment]
When I surround the search text by double quotes, the percentage signs are still included. It would be nice if this can be avoided, perhaps per data provider?

**Comment by seanthomasdevlin** [comment]
Vincent, sorry for the slow reply - I didn't see this comment.
The quotes are meant to escape the space (similar to google)
"servoy world" // matches only terms LIKE %servoy world%
servoy world // matches all terms LIKE %servoy% and all terms LIKE %world%, splitting on the space
