### ISSUE TITLE
Date entry throws error on unexpected character.

### ISSUE THREAD

**Issue by kimpremuda** [Servoy/svySearch#12]
Date entry throws error on unexpected character. See graphic...look for semicolon in search field (upper right hand corner of image).

![svysearch_date_failure_on_unexpected_character](https://cloud.githubusercontent.com/assets/25161118/23324505/059b7d60-faa3-11e6-98cf-6325c7a6e166.png)

**Comment by seanthomasdevlin** [comment]
Kim, did you put the semicolon there yourself?

**Comment by kimpremuda** [comment]
It was initially discovered as a typo by someone else, but, yes, I put the semicolon in the example to reproduce the issue. I was thinking the date parser could use regex to test for correct operator form, so as to prevent errors.

**Comment by seanthomasdevlin** [comment]
Hi Kim,
No, but there should be better error handling here.
The idea behind this lib is that you wouldn't normally show any errors to an end user.
It should really just log the problem and skip the token (as it does with other problems)
I will look to fix this.

But as a developer, you may want to custom handle when user input could not be parsed
The parsing method is currently private, but we consider to make it public so it can be called independently. This is on the planning for this lib.

There are others who do just that now (ignoring warnings to call a private method)
Then they can determine if there was a problem and show their user

**Comment by kimpremuda** [comment]
I am OK with logging the error and skipping the token as long as the end-user doesn't have to contend with the error message. Thanks for looking into this!

**Comment by seanthomasdevlin** [comment]
this was resolved with try/catch on parse date. Error is logged but search fails silent to the user (for smart client)

**Comment by kimpremuda** [comment]
Sean,

 

Thank you, thank you, thank you!

 

Kim W. Premuda

 

     *619-596-9404 Office     '858-487-1400 Cell     * <mailto:kim@armsd.com> kim@armsd.com     * <http://www.armsd.com/> www.armsd.com
