### ISSUE TITLE
dataProviderId already found

### ISSUE THREAD

**Issue by pdeg001** [Servoy/svySearch#2]
When a dataProviderId is already in the searchProviders svySearch terminates, but I think it's very common that a dataProvider is used multiple times on, in our case, a form. I think that if the dataProvider already exist it should be ignored and the routine should continue.

Regards,

Peter de Groot

**Comment by seanthomasdevlin** [comment]
Hi Peter,

That is expected behavior. If you try to add multiple references to the same data provider, it will be rejected. Please explain why you want to add a data provider multiple times.

Please provide a code example (and search string) that you are trying to use.

Best,
Sean

**Comment by pdeg001** [comment]
Hi Sean,

what I did for an solution that has an search option for all the fields on the main screen is,
I created a method that retrieves all the fields visible, including all fields on tabpanels, something like this,
```
        $search = scopes.svySearch.createSimpleSearch(foundset);
	$search.setDateFormat('dd-MM-yyyy');

	getDataproviders();

	/**GET DATAPROVIDERS*/
	function getDataproviders() {
		var $solForm, $labels, $i, $j, $k, $field, $dataProvider, $alias, $panels;

		$solForm = solutionModel.getForm('mnem_projects');
		$labels = $solForm.getLabels();

		for ($i in $labels) {
			if ($labels[$i].labelFor) {

				$alias = utils.stringReplace($labels[$i].text, ' ', '').toLowerCase();
				$field = $solForm.getField($labels[$i].labelFor).dataProviderID;
				
				$seachFieldsRealArr.push([$alias, $labels[$i].text]);
				//$seachFieldsDispArr.push($labels[$i].text);
				
				$search.addSearchProvider($field).setAlias($alias);
			}
		} 
                .
                .
                $search.addSearchProvider($field).setAlias($alias);
```

The addSearchProvider checks for existing dataProviders

```
for(var i in searchProviders){
    if(searchProviders[i].getDataProviderID() == dataProviderID){
         throw new scopes.svyExceptions.IllegalArgumentException('Search Provider already found: ' + dataProviderID);
    }
}
```

It would be nice that when a existing dataProvider is found in the code above ignores the duplicate and just continues instead of throwing an error.  

I know I can handle duplicates in getDataproviders(); but I think it would be nicer if svySearch handles the duplicates.

Regards,
Peter

**Comment by seanthomasdevlin** [comment]
Hi Peter,

Thanks for the clarification. Yes, we can suppress the error and instead log a warning.
If the data provider already exists, we can **overwrite** it and log a warning.
