### ISSUE TITLE
New release required 

### ISSUE THREAD

**Issue by SteveHawes** [Servoy/svySearch#21]
The last release of this module was in 2016 and since then there have been some good fixes/improvements such as the implied search on non-text fields. Please can we have an updated release so that new (and existing) projects can benefit from these without having to use the source from Git. 

Servoy now includes this module in new projects by default so it makes no sense for it not to be updated.

Thanks.

**Comment by seanthomasdevlin** [comment]
Hi Steve,

Thanks for using SvySearch.

We have closed all outstanding issues and built a [new release](https://github.com/Servoy/svySearch/releases/tag/v1.2.0). Please see release notes and updated [wiki docs](https://github.com/Servoy/svySearch/wiki)

If you find any issues post them here. Thanks!
