### ISSUE TITLE
SQL-Error when searching in date-field and alternative-dateformat "yyyy" is defined

### ISSUE THREAD

**Issue by philippr71** [Servoy/svySearch#27]
To reproduce the issue:

- create a table with at least an integer column and a date column (SQL-Server-Type "datetime2")
- define the following alternative dateformats for searching:
	search.setDateFormat("dd.MM.yyyy");
	search.addAlternateDateFormat("MM.yyyy");
	search.addAlternateDateFormat("yyyy");

If you search for a value that could be a valid year, then it workes well. For example search value "2018".

But it produces the sql-error "com.servoy.j2db.dataprocessing.DataException: Unbekannter Fehler
Für den SQL Server-Datentyp "datetime2" liegt mindestens ein Wert außerhalb des gültigen Wertebereichs." when you search for example for the value "21039".

If you remove the last alternative-date-format (the only-year-search), then the error is gone.

**Comment by paronne** [comment]
Hi Roland,

thanks for reporting the issue. I have created a case in our support system
You can follow progress for: https://support.servoy.com/browse/SVYX-317

**Comment by seanthomasdevlin** [comment]
Hi Roland,

It seems that the dat was parsed correctly, but the year is exceeding the max for SQL server (9999). This explains why it was not rejected for PostgreSQL.

Now any parsed dates having a year > 9999 will be ignored for a datetime column.

This will be included in the next release. You can pull from source to test immediately.
